apiVersion: triggers.tekton.dev/v1beta1 
kind: TriggerBinding
metadata:
  name: trigger-rd-pipeline-bingding
  namespace: demo
spec:
  params:
    - name: gitrevision
      value: $(body.ref)
    - name: namespace
      value: tekton-devops-pipeline
    - name: gitrepositoryurl
      value: http://192.168.4.79/root/tkn-ops.git
      #value: $(body.project.git_http_url)
    - name: projectname
      value: $(body.project.name)
