apiVersion: v1
kind: Secret
metadata:
  name: gitlab-auth
  namespace: demo
  annotations:
    tekton.dev/git-0: http://192.168.4.79/
type: kubernetes.io/basic-auth
stringData:
  username: root
  password: 1W7pGoSZAeEs1l_T_dtrP
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tekton-build-sa
  namespace: demo
secrets:
  - name: gitlab-auth
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tekton-clusterrole-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
subjects:
  - kind: ServiceAccount
    name: tekton-build-sa
    namespace: demo
