---
apiVersion: v1
kind: Service
metadata:
  name: httpserver
  namespace: {{ .Values.namespace }}
spec:
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: http
  selector:
    app: httpserver
  sessionAffinity: None
  type: NodePort
